name:                HuttonBook
version:             0.1.0.0
github:              "chroth7/HuttonBook"
license:             BSD3
author:              "Christian Roth"
maintainer:          "chroth@me.com"
copyright:           "2019 Christian Roth"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HuttonBook#readme>

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.7 && < 3
- QuickCheck >= 2.13 && < 3

library:
  source-dirs: src

executables:
  HuttonBook-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HuttonBook

tests:
  HuttonBook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HuttonBook
